# Generated by Django 5.2.4 on 2025-08-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_deal',
            field=models.BooleanField(default=False),
        ),
    ]
