# Generated by Django 5.1.1 on 2025-08-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_category_image_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Holder Name'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Internal notes for this return.', null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('Original', 'Refund to Original Payment Method'), ('Bank', 'Refund to Bank Account')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_processed',
            field=models.BooleanField(default=False),
        ),
    ]
