# Generated by Django 5.1.1 on 2025-08-08 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_delivered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="The coupon code customers will enter (e.g., 'SALE50').", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text="Text to display on the homepage deal (e.g., 'Special Diwali Offer').", max_length=100)),
                ('valid_from', models.DateTimeField(help_text='The date and time from which the coupon is valid.')),
                ('valid_to', models.DateTimeField(help_text='The date and time until which the coupon is valid.')),
                ('discount_percent', models.IntegerField(help_text='Discount percentage (e.g., 15 for 15%).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField(default=True, help_text='Is the coupon currently active?')),
                ('show_on_homepage', models.BooleanField(default=False, help_text='Check this to show the coupon deal on the homepage.')),
            ],
            options={
                'ordering': ['-valid_to'],
            },
        ),
    ]
