# Generated by Django 5.1.1 on 2025-08-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Select products that go well with this item.', to='store.product', verbose_name="Related Products (for 'Complete the Look')"),
        ),
    ]
