# Generated by Django 5.1.1 on 2025-08-10 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Market Price'),
        ),
        migrations.CreateModel(
            name='DealOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_price', models.DecimalField(decimal_places=2, help_text='The special discounted price for the deal.', max_digits=10)),
                ('end_time', models.DateTimeField(help_text='The date and time when this deal will end.')),
                ('active', models.BooleanField(default=True, help_text='Is this deal currently active?')),
                ('product', models.OneToOneField(help_text='Select the product for the deal.', on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Deal of the Day',
            },
        ),
    ]
